### PR TITLE
Update dismiss button click

### PR DESCRIPTION
**Pull request by sobuj53**
updated method to work with latest colab change

### CODE REVIEW

**Comment by sobuj53** [comment]
this probably won't work as expected, can you grab button id of this?
image

**Comment by rtindru** [comment]
I'm noticing that a second click on the "Connect" tab auto-closes the resource dialog. Should we just do that instead?
See: https://www.dropbox.com/s/7q09nf7s14tq1kk/Recording%204-1-21%20at%203.10.01%20PM.mp4?dl=0

**Comment by sobuj53** [comment]
My current pull request is actually based on that principle, however it doesn't work properly, eg. if you were to click the connect button and at the same time if the schedule kicks in then, instead of closing the box on second click, it will pop open! So the only reliable way would be to click the cross button to make sure the dialogue box closes. That's why we need to find the button id.

**Comment by sobuj53** [comment]
this doesn't work properly so closing it.

**Pull request closed without merging**
